# CMake generated Testfile for 
# Source directory: /Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator
# Build directory: /Users/anupkaul/akaul_git/deepmind/build_mujoco_mpc/mjpc/test/estimator
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BatchFilter.Box3Drot "/Users/anupkaul/akaul_git/deepmind/build_mujoco_mpc/bin/batch_filter_test" "--gtest_filter=BatchFilter.Box3Drot")
set_tests_properties(BatchFilter.Box3Drot PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;15;test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;0;")
add_test(PriorCost.Particle "/Users/anupkaul/akaul_git/deepmind/build_mujoco_mpc/bin/batch_prior_test" "--gtest_filter=PriorCost.Particle")
set_tests_properties(PriorCost.Particle PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;18;test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;0;")
add_test(PriorCost.Box "/Users/anupkaul/akaul_git/deepmind/build_mujoco_mpc/bin/batch_prior_test" "--gtest_filter=PriorCost.Box")
set_tests_properties(PriorCost.Box PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;18;test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;0;")
add_test(Estimator.Kalman "/Users/anupkaul/akaul_git/deepmind/build_mujoco_mpc/bin/kalman_test" "--gtest_filter=Estimator.Kalman")
set_tests_properties(Estimator.Kalman PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;21;test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;0;")
add_test(Unscented.Particle1D "/Users/anupkaul/akaul_git/deepmind/build_mujoco_mpc/bin/unscented_test" "--gtest_filter=Unscented.Particle1D")
set_tests_properties(Unscented.Particle1D PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;24;test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;0;")
add_test(Unscented.Box3Drot "/Users/anupkaul/akaul_git/deepmind/build_mujoco_mpc/bin/unscented_test" "--gtest_filter=Unscented.Box3Drot")
set_tests_properties(Unscented.Box3Drot PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;24;test;/Users/anupkaul/akaul_git/deepmind/mujoco_mpc/mjpc/test/estimator/CMakeLists.txt;0;")
