# CMake generated Testfile for 
# Source directory: /Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct
# Build directory: /Users/anupkaul/other_git/deepmind/build_mujoco_mpc/mjpc/test/direct
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ForceCost.Particle "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_force_test" "--gtest_filter=ForceCost.Particle")
set_tests_properties(ForceCost.Particle PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;15;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(ForceCost.Box "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_force_test" "--gtest_filter=ForceCost.Box")
set_tests_properties(ForceCost.Box PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;15;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(ForceCost.ParticleDamped "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_force_test" "--gtest_filter=ForceCost.ParticleDamped")
set_tests_properties(ForceCost.ParticleDamped PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;15;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(DirectParameter.ParticleFramePos "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_parameter_test" "--gtest_filter=DirectParameter.ParticleFramePos")
set_tests_properties(DirectParameter.ParticleFramePos PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;18;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(DirectOptimize.Particle2D "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_optimize_test" "--gtest_filter=DirectOptimize.Particle2D")
set_tests_properties(DirectOptimize.Particle2D PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;21;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(DirectOptimize.Box3D "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_optimize_test" "--gtest_filter=DirectOptimize.Box3D")
set_tests_properties(DirectOptimize.Box3D PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;21;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(SensorCost.Particle "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_sensor_test" "--gtest_filter=SensorCost.Particle")
set_tests_properties(SensorCost.Particle PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;24;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(SensorCost.Box "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_sensor_test" "--gtest_filter=SensorCost.Box")
set_tests_properties(SensorCost.Box PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;24;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(DirectTrajectory.Test "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_trajectory_test" "--gtest_filter=DirectTrajectory.Test")
set_tests_properties(DirectTrajectory.Test PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;27;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(FiniteDifferenceVelocityAcceleration.Particle1D "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_utilities_test" "--gtest_filter=FiniteDifferenceVelocityAcceleration.Particle1D")
set_tests_properties(FiniteDifferenceVelocityAcceleration.Particle1D PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;30;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
add_test(FiniteDifferenceVelocityAcceleration.Box3D "/Users/anupkaul/other_git/deepmind/build_mujoco_mpc/bin/direct_utilities_test" "--gtest_filter=FiniteDifferenceVelocityAcceleration.Box3D")
set_tests_properties(FiniteDifferenceVelocityAcceleration.Box3D PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/CMakeLists.txt;31;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;30;test;/Users/anupkaul/other_git/deepmind/mujoco_mpc/mjpc/test/direct/CMakeLists.txt;0;")
